go-filecoin-tutorial/Home.md
A few edits to make it more clear that this site is only focused on one implementation and to surface the new docs site.
=> Clarify that this is the go-filecoin site

go-filecoin-tutorial/Getting-Started.md
Link fixes in the getting started section
=> Link fixes

go-filecoin-tutorial/Troubleshooting-&-FAQ.md
Adds instructions for changing ports to the Troubleshooting page. Reference: https://gist.githubusercontent.com/ZenGround0/0e89a51f1491cb5ca169a33a4bfd829d/raw/66e674f666624a6b37a58c77cec698c3ed4415bb/gfc-static-port.md
=> Adds instructions to change ports

go-filecoin-tutorial/How-to-connect-two-nodes-directly.md
=> Clean-up, connecting two nodes directly page

go-filecoin-tutorial/Mining-Filecoin.md
=> Clean-up, mining filecoin page

go-filecoin-tutorial/Running-a-network-locally.md
=> Clean-up, local network page

go-filecoin-tutorial/Storing-on-Filecoin.md
=> Clean-up, storage page

README.md
I added more details about deploy & updating navigation. I mention the name of the private repo, if you disagree feel free to edit.
=> Add deploy details

go-filecoin-tutorial/Home.md
Updates home to reflect doc changes
=> Links removal

go-filecoin-tutorial/Getting-Started.md, go-filecoin-tutorial/Mining-Filecoin.md
=> add filfox.io to explorers

docs/Chain.md
=> add chain.md

docs/Venus wallet.md, docs/venus_load_balancing.md, docs/zh/How to use venus messager.md, docs/zh/Tips-Running-In-China.md
Venus wallet.md 
venus_load_balancing.md
How to use venus messager.md
Tips-Running-In-China.md
=> Docs update

.gitignore, docs/Using-venus-Shared-Modules.md
Fix some wording for join mining pool doc.
=> Join mining pool doc quick fix

docs/.vuepress/config.js, docs/incubation/Rules.md, docs/zh/incubation/Rules.md
add detailed rules about incubation under /incubation/
=> add incubation rules page

docs/modules/How-To-Use-Wallet-In-Venus.md
After execute locked wallet, this should get locked success here
=> After execute locked wallet, this should get locked success here

docs/guide/How-To-Deploy-MingPool.md, docs/guide/Using-venus-Shared-Modules.md
=> add market modules

docs/zh/modules/How-To-Use-Wallet-In-Venus.md
After execute locked wallet, this should get locked success here
=> zh docs: After execute locked wallet, this should get locked success here

docs/zh/advanced/venus-gateway-system-design.md
=> venus gateway system design

docs/guide/Using-venus-Shared-Modules.md, docs/modules/README.md, docs/zh/guide/Using-venus-Shared-Modules.md, docs/zh/modules/README.md
2. Add module default port
3. Add more about wallet module ,because the state of wallet unlock block the sealer init
=> 1. Fix the wrong calibration url

docs/guide/How-To-Connect-Network.md, docs/guide/How-To-Deploy-MingPool.md, docs/guide/README.md, docs/guide/Using-venus-Shared-Modules.md, docs/guide/Using-venus-cluster.md, docs/incubation/announcement.md, docs/master/README.md, docs/mine/hardware-requirements.md, docs/modules/Venus-Worker.md, docs/zh/advanced/Venus-Project-Dependency-Upgrade.md, docs/zh/guide/How-To-Connect-Network.md, docs/zh/guide/How-To-Deploy-MingPool.md, docs/zh/guide/README.md, docs/zh/guide/Using-venus-Shared-Modules.md, docs/zh/guide/Using-venus-cluster.md, docs/zh/incubation/announcement.md, docs/zh/master/Chain_service_construction.md, docs/zh/mine/hardware-requirements.md, docs/zh/modules/Venus-Worker.md
Remove Nerpa network related information
=> change nerpa

docs/guide/Using-venus-Shared-Modules.md, docs/modules/Venus-Worker.md, docs/zh/modules/Venus-Worker.md
Modify the default sector size of Cali network and the reference case of venus-worker.
=> change sectors size and test case

docs/zh/guide/using-venus-market-for-miner.md
=> feat: snapdeal: snapdeal document

docs/zh/guide/How-To-Deploy-MingPool.md
Solve the problem that Venus-miner cannot view the new miner information.
=> Venus miner cannot display miner list

docs/guide/How-To-Deploy-MingPool.md, docs/guide/Using-venus-Shared-Modules.md, docs/modules/Venus-Auth.md, docs/zh/guide/How-To-Deploy-MingPool.md, docs/zh/guide/Using-venus-Shared-Modules.md, docs/zh/market/using-venus-market-for-miner.md, docs/zh/master/Chain_service_construction.md, docs/zh/modules/Venus-Auth.md
=> feat : update venus-auth usage

docs/zh/market/using-venus-market-for-master.md
=> change node port number from 3454 to 3453

docs/.vuepress/config.js, docs/zh/cs/venus-run-in-docker.md
correct title spelling
update the link of docker script
=> fix : docekr : update docker script link

.github/workflows/publish.yaml
fix filecoin-project/venus#4933
=> feat: #4933 venus-docs : auto publish docs when push or merge pr

docs/.vuepress/config.js, docs/market/prep-datasets.md
https://github.com/filecoin-project/venus-docs/pull/318 的英文版。
=> docs: add en prep datasets

docs/zh/cs/venus-run-in-docker.md
fix https://github.com/filecoin-project/venus/issues/4973
remove  redundant link in docker docs
=> fix #4937 :  venus docs ： rm redundant link in docker docs

script/docker-compose.yaml
https://github.com/filecoin-project/venus/issues/4974 
set snapshot.car var a default value which to be the default way of car file
=> feat: make snapshot optional

script/docker-compose.yaml
fix https://github.com/filecoin-project/venus/issues/5014
make it possibel to set time zone by env  var $TZ
=> feat #50014 : venus docker compose :  make it possibel to set time zone by env  var $TZ

docs/cs/join-a-cs.md, docs/zh/cs/join-a-cs.md
fix https://github.com/filecoin-project/venus/issues/5031
=> docs: fix venus-cluster for readability

script/docker-compose.yaml
close https://github.com/filecoin-project/venus/issues/5024
As described in title
=> chore: change market boot order dependency from venus daemon to messager

docs/zh/market/using-venus-market-for-miner.md
involve https://github.com/filecoin-project/venus/issues/5088
link the part which discuss how to config PieceStorage of market to the docs of venus-market
=> doc: 更新venus-market 配置相关的文档 /  update doc about venus market

docs/zh/cs/venus-run-in-docker.md, script/docker-compose.yaml
involve https://github.com/filecoin-project/venus/issues/5240
- update docs about usage of docker image
- update docker-compose setting
=> feat: update docker-compose setting  and docs

script/dockerfile
- rm default bin name in dockerfile
=> fix: rm default bin name in dockerfile

docs/zh/cs/deploy-a-cs.md, docs/zh/market/using-venus-market-for-master.md, docs/zh/market/using-venus-market-for-miner.md
修改venus-miner初始化信息和venus-market改变worker地址后无法发单问题
=> 更新venus-miner初始化和venus-market说明

docs/advanced/How-To-Connect-Network.md, docs/advanced/How-To-Setup_2knet.md, docs/cs/deploy-a-cs.md, docs/operation/README.md, docs/operation/Venus-HA.md, docs/zh/advanced/How-To-Connect-Network.md, docs/zh/cs/deploy-a-cs.md, docs/zh/cs/venus-run-in-docker.md, docs/zh/master/Chain_service_construction.md, docs/zh/operation/README.md, docs/zh/operation/Venus-HA.md
https://github.com/filecoin-project/venus/issues/5187
=> docs: update network name & rename chain-ro to chain-co

docs/zh/market/prep-datasets.md
correct the piece size calculation.
close
=> fix: `slice-size` calculation error

docs/.vuepress/config.js, docs/operation/nv17-upgrade.md, docs/zh/operation/nv17-upgrade.md
close https://github.com/filecoin-project/venus/issues/5481
=> add nv17 upgrade doc

script/docker/compose/venus-market.sh
=> feat: update market run mod /升级 market 的运行模式

Makefile, script/docker/compose/venus-market.sh
=> fix: update market cmd / 修复 market 执行的命令

docs/cluster/getting-started.md
最新版本的 venus-cluster 已经不需要 `--net` 参数了
=> venus-cluster: Remove `--net` flag

docs/zh/cs/venus-run-in-docker.md
=> feat: update docker docs / 更新 docker 的文档  

docs/.vuepress/config.js, docs/operation/nv18-upgrade.md, docs/zh/operation/nv18-upgrade.md
close https://github.com/filecoin-project/venus/issues/5787
=> add nv18 doc

docs/.vuepress/config.js
close https://github.com/filecoin-project/venus/issues/5825
=> fix: update droplet api ref / 更新水滴 API 文档

script/download.js
close https://github.com/filecoin-project/venus/issues/5826
=> feat: auto create parent directory / 自动创建父目录

docs/advanced/How-To-Setup_2knet.md, docs/operation/README.md, docs/zh/advanced/How-To-Setup_2knet.md, docs/zh/master/Chain_service_construction.md, docs/zh/operation/README.md, script/docker/compose/venus-gateway.sh, script/docker/compose/venus-wallet.sh
close https://github.com/filecoin-project/venus/issues/5905
=> docs: add --auth-token flag

docs/.vuepress/config.js, docs/operation/nv19-upgrade.md, docs/zh/operation/nv19-upgrade.md
close https://github.com/filecoin-project/venus/issues/5928
=> add nv19 upgrade guide

docs/zh/operation/nv19-upgrade.md
=> feat: update nv19 upgrade doc / 更新 nv19 升级文档

.github/dependabot.yml, .github/workflows/build_docker_buildenv.yaml, .github/workflows/build_docker_runtime.yaml, .github/workflows/publish.yaml
Updates GitHub Actions actions versions and configures dependabot to auto-update actions in the future. Related to https://filecoinproject.slack.com/archives/C03KLC57LKB/p1686680229440949
=> chore: update github actions

docs/about/README.md
https://github.com/ipfs-force-community/venus-core-devs/issues/12
=> fix CI fail

Makefile, script/docker/venus-buildenv.dockerfile
=> feat: update go version and image version

Makefile, script/docker/venus-buildenv.dockerfile
=> feat/bump up go version of build env to 1.20

script/docker/dockerfile
=> feat: use latest tag for docker image

docs/.vuepress/config.js, package-lock.json, package.json, yarn.lock
related https://github.com/ipfs-force-community/venus-core-devs/issues/23
=> add full text search

docs/operation/README.md
close https://github.com/ipfs-force-community/venus-core-devs/issues/25
=> update en arch img

docs/operation/nv21-upgrade.md, docs/zh/operation/nv21-upgrade.md
=> doc: update doc of nv21 upgrade

docs/.vuepress/config.js, docs/operation/nv22-upgrade.md, docs/zh/operation/nv22-upgrade.md
close https://github.com/ipfs-force-community/venus-core-devs/issues/26
=> add nv22 upgrade guide

docs/operation/nv22-upgrade.md, docs/zh/operation/nv22-upgrade.md
close https://github.com/ipfs-force-community/venus-core-devs/issues/26
=> update venus version

docs/operation/nv22-upgrade.md
close https://github.com/ipfs-force-community/venus-core-devs/issues/26
=> Fix typos in nv22-upgrade.md

Makefile, script/docker/venus-buildenv.dockerfile
=> feat: update docker build env

Makefile, script/docker/venus-buildenv.dockerfile
=> feat: update golang version of  build env to 1.23
